#!/usr/bin/env bash
# a Bash script that installs nginx on our web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Holberton School
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
service nginx start
