#!/usr/bin/env bash
# configuration of web-02 server

sudo apt-get -y update
sudo apt-get -y install ngnix
sudo service ngnix start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
