#!/usr/bin/env bash
# Install nginx and configute a new server
# Listening on port 80.
# Have a custom "Hello World" page when yo visit
# Have a redirect page
# Have a custom 404 page
# Have a custom header named X-Served-By

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/custom404.html
echo "Ceci n'est pas une page" > /var/www/html/custom404.html

server="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
    error_page 404 /custom404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}"
sudo echo > /etc/nginx/sites-available/default

sudo service nginx restart
