#!/usr/bin/env bash
# install Haproxy
# configure HAproxy
sudo aot-get  -y update
sudo apt-get -y upgrade

# Add Haproxy PPA
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo app-get -y update

# Install Haproxy
sudo apt-get -y install haproxy=2.5.\*

# Configure Haproxy
config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends
backend lb-backends
    balance roundrobin
    server 154836-web-01 54.197.117.171:80 check
    server 154836-web-02 52.3.247.208:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
