#!/usr/bin/env bash
# install Haproxy
# configure HAproxy
sudo aot-get  -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 154836-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 154836-web-02 52.3.247.208:80 check\n\tserver 154836-web-01 54.197.117.171:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
